In [1]:
import numpy as np
import pandas as pd

from trading_environment import TradingEnv
from utils import load_data
from indicators import get_momentum_strategy

In [2]:
data_df = load_data("data/Bitfinex_BTCUSD_1h_2019")
# data_df = load_data("data/Bitfinex_BTCUSD_1h_2019", strategy=get_momentum_strategy())
data_df.head(8)

Date     Open    High      Low    Close      Volume
0  1/1/2019 0:00  3830.50  3846.2  3822.40  3835.16  1032854.96
1  1/1/2019 1:00  3835.16  3840.1  3819.00  3829.15  1440314.68
2  1/1/2019 2:00  3829.15  3834.2  3810.20  3817.40  1624863.73
3  1/1/2019 3:00  3817.40  3832.3  3817.30  3828.40   676778.97
4  1/1/2019 4:00  3828.40  3844.9  3824.50  3825.00  1179209.23
5  1/1/2019 5:00  3825.00  3833.3  3823.00  3833.30   567718.43
6  1/1/2019 6:00  3833.30  3839.1  3827.30  3833.21   752878.69
7  1/1/2019 7:00  3833.21  3868.0  3833.21  3851.00  3354240.14

In [3]:
env = TradingEnv(data_df, window_size=5)
env.reset()
print(env.get_observation())
# env.df[env.current_step-env.window_size: env.current_step]

[[3835.16]
 [3829.15]
 [3817.4 ]
 [3828.4 ]
 [3825.  ]]


In [4]:
# env.step([])
# env.df[env.current_step-env.window_size: env.current_step]

In [5]:
# done = False
# while not done:
#     orders = [{"order_type": "open_long", "amount": 10}]
#     next_state, reward, done = env.step(orders)
# env.current_step

In [6]:
# open long
for i in range(5):
    orders = [{"order_type": "open_long", "amount": 100}]
    next_state, reward, done = env.step(orders)
    print(f"Reward:{reward}")

print(env.getCurrentPrice(), env.getBalance(), env.getNetWorth())
env.getCurrentPostion()

Reward:0
Reward:0
Reward:0
Reward:0
Reward:0
3855.6 9500.0 10000.9016865511


Date  Id  Type  EntryPrice    Amount       PNL   pChange
0   1/1/2019 6:00   0  long     3833.21  0.026088  0.584106  0.584106
1   1/1/2019 7:00   1  long     3851.00  0.025967  0.119449  0.119449
2   1/1/2019 8:00   2  long     3859.60  0.025909 -0.103638 -0.103638
3   1/1/2019 9:00   3  long     3844.00  0.026015  0.301769  0.301769
4  1/1/2019 10:00   4  long     3855.60  0.025936  0.000000  0.000000

In [7]:
# close long
orders = [{"order_type": "close_long", "id": 4}]
next_state, reward, done =env.step(orders)
print(env.getCurrentPrice(), env.getBalance(), env.getNetWorth())
print(reward)
env.getCurrentPostion()

3850.6 9599.87031849777 10000.252109719284
0


Date  Id  Type  EntryPrice    Amount       PNL   pChange
0  1/1/2019 6:00   0  long     3833.21  0.026088  0.453667  0.453667
1  1/1/2019 7:00   1  long     3851.00  0.025967 -0.010387 -0.010387
2  1/1/2019 8:00   2  long     3859.60  0.025909 -0.233185 -0.233185
3  1/1/2019 9:00   3  long     3844.00  0.026015  0.171696  0.171696

In [8]:
env.date, env.prices, env.features

(array(['1/1/2019 0:00', '1/1/2019 1:00', '1/1/2019 2:00', ...,
        '31/12/2019 21:00', '31/12/2019 22:00', '31/12/2019 23:00'],
       dtype=object),
 array([3835.16, 3829.15, 3817.4 , ..., 7197.4 , 7217.  , 7208.3 ]),
 array([[1032854.96],
        [1440314.68],
        [1624863.73],
        ...,
        [ 653015.01],
        [1333111.29],
        [1092539.24]]))